PruebasRazor/Models/Viaje.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebasRazor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Viaje()
        {
            this.Asiento = new HashSet<Asiento>();
            this.DETALLEVENTA = new HashSet<DETALLEVENTA>();
        }
    
        public int IIDVIAJE { get; set; }
        public Nullable<int> IIDLUGARORIGEN { get; set; }
        public Nullable<int> IIDLUGARDESTINO { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public Nullable<System.DateTime> FECHAVIAJE { get; set; }
        public Nullable<int> IIDBUS { get; set; }
        public Nullable<int> NUMEROASIENTOSDISPONIBLES { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
        public byte[] FOTO { get; set; }
        public string nombrefoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asiento> Asiento { get; set; }
        public virtual Bus Bus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLEVENTA> DETALLEVENTA { get; set; }
        public virtual Lugar Lugar { get; set; }
        public virtual Lugar Lugar1 { get; set; }
    }
}

PruebasRazor/Controllers/ViajeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PruebasRazor.Models;
namespace PruebasRazor.Controllers
{
    public class ViajeController : Controller
    {
        // GET: Viaje
        public ActionResult Index()
        {
            List<ViajeCLS> listaViaje = null;
            using (var bd = new BDPasajeEntities())
            {
                listaViaje = (from viaje in bd.Viaje
                              where viaje.BHABILITADO==1
                              join lugarOrigen in bd.Lugar
                              on viaje.IIDLUGARORIGEN equals lugarOrigen.IIDLUGAR
                              join lugarDestino in bd.Lugar
                              on viaje.IIDLUGARDESTINO equals lugarDestino.IIDLUGAR
                              join bus in bd.Bus
                              on viaje.IIDBUS equals bus.IIDBUS
                              select new ViajeCLS
                              {
                                  iidViaje = viaje.IIDVIAJE,
                                  nombreBus = bus.PLACA,
                                  nombreLugarDestino = lugarOrigen.NOMBRE,
                                  nombreLugarOrigen = lugarDestino.NOMBRE
                              }).ToList();
            }
                return View(listaViaje);
        }

        public void listarLugar()
        {
            List<SelectListItem> lista;
            using (var bd = new BDPasajeEntities())
            {
                lista = (from item in bd.Lugar
                         where item.BHABILITADO == 1
                         select new SelectListItem
                         {
                             Text = item.NOMBRE,
                             Value = item.IIDLUGAR.ToString()
                         }).ToList();
                lista.Insert(0, new SelectListItem { Text = "--Seleccione--", Value = "" });
                ViewBag.listaLugar = lista;
            }
        }

        public void listarBus()
        {
            List<SelectListItem> lista;
            using (var bd = new BDPasajeEntities())
            {
                lista = (from item in bd.Bus
                         where item.BHABILITADO == 1
                         select new SelectListItem
                         {
                             Text = item.PLACA,
                             Value = item.IIDBUS.ToString()
                         }).ToList();
                lista.Insert(0, new SelectListItem { Text = "--Seleccione--", Value = "" });
                ViewBag.listaBus = lista;
            }
        }

        public void listarCombos() {
            listarBus();
            listarLugar();
        }

        public ActionResult Agregar()
        {
            listarCombos();
            return View();
        }

        public ActionResult Editar(int id)
        {
            listarCombos();
            ViajeCLS oViajeCLS = new ViajeCLS();
            using (var bd = new BDPasajeEntities())
            {
                Viaje oViaje = bd.Viaje.Where(p => p.IIDVIAJE.Equals(id)).First();
                oViajeCLS.iidViaje = oViaje.IIDVIAJE;
                oViajeCLS.precio = (decimal) oViaje.PRECIO;
                oViajeCLS.iidLugarDestino = (int) oViaje.IIDLUGARDESTINO;
                oViajeCLS.iidLugarOrigen = (int) oViaje.IIDLUGARORIGEN;
                oViajeCLS.fechaViaje = (DateTime) oViaje.FECHAVIAJE;
                oViajeCLS.iidBus = (int) oViaje.IIDBUS;
                oViajeCLS.numeroAsientosDisponibles = (int) oViaje.NUMEROASIENTOSDISPONIBLES;
            }
            return View(oViajeCLS);
        }

        [HttpPost]
        public ActionResult Editar(ViajeCLS oViajeCLS)
        {
            int idviaje = oViajeCLS.iidViaje;
            if (!ModelState.IsValid)
            {
                listarCombos();
                return View(oViajeCLS);
            }
            using (var bd = new BDPasajeEntities())
            {
                Viaje oViaje = bd.Viaje.Where(p => p.IIDVIAJE.Equals(idviaje)).First();
                oViaje.IIDVIAJE = oViajeCLS.iidViaje;
                oViaje.PRECIO = oViajeCLS.precio;
                oViaje.IIDLUGARDESTINO = oViajeCLS.iidLugarDestino;
                oViaje.IIDLUGARORIGEN = oViajeCLS.iidLugarOrigen;
                oViaje.FECHAVIAJE = oViajeCLS.fechaViaje;
                oViaje.IIDBUS = oViajeCLS.iidBus;
                oViaje.NUMEROASIENTOSDISPONIBLES = oViajeCLS.numeroAsientosDisponibles;
                bd.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Agregar(ViajeCLS oViajeCLS)
        {
            //puede haber varios viajes al dia con estas caracteristicas
            if (!ModelState.IsValid)
            {
                listarCombos();
                return View(oViajeCLS);
            }
            using (var bd = new BDPasajeEntities())
            {
                Viaje oViaje = new Viaje();
                oViaje.IIDLUGARORIGEN = oViajeCLS.iidLugarOrigen;
                oViaje.IIDLUGARDESTINO = oViajeCLS.iidLugarDestino;
                oViaje.PRECIO = oViajeCLS.precio;
                oViaje.FECHAVIAJE = oViajeCLS.fechaViaje;
                oViaje.IIDBUS = oViajeCLS.iidBus;
                oViaje.NUMEROASIENTOSDISPONIBLES = oViajeCLS.numeroAsientosDisponibles;
                oViaje.BHABILITADO = 1;
                bd.Viaje.Add(oViaje);
                bd.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Eliminar(int txtIdViaje)
        {
            using (var bd = new BDPasajeEntities())
            {
                Viaje oViaje = bd.Viaje.Where(p => p.IIDVIAJE.Equals(txtIdViaje)).First();
                oViaje.BHABILITADO = 0;
                bd.SaveChanges();
            }
            return RedirectToAction("Index");
        }

    }
}

PruebasRazor/Views/Viaje/Agregar.cshtml
@model PruebasRazor.Models.ViajeCLS

@{
    ViewBag.Title = "Agregar";
    List<SelectListItem> listaBus = (List<SelectListItem>)ViewBag.listaBus;
    List<SelectListItem> listaLugar = (List<SelectListItem>)ViewBag.listaLugar;
}

<h2>Agregar</h2>

@using (Html.BeginForm("Agregar", "Viaje", FormMethod.Post, new { @id = "frmAgregar" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ViajeCLS</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.iidLugarOrigen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("iidLugarOrigen", listaLugar, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.iidLugarOrigen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.iidLugarDestino, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("iidLugarDestino", listaLugar, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.iidLugarDestino, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fechaViaje, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fechaViaje, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fechaViaje, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.iidBus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("iidBus", listaBus, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.iidBus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.numeroAsientosDisponibles, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.numeroAsientosDisponibles, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.numeroAsientosDisponibles, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div style="margin:auto">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                    Guardar
                </button>
                @Html.ActionLink("Volver", "Index", "Viaje", null, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
}


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">¿Guardar Cambios?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div style="padding:1em">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">CANCELAR</button>
                <button type="button" onclick="Agregar()" class="btn btn-primary">ACEPTAR</button>
            </div>
        </div>
    </div>
</div>

<script>
    function Agregar() {
        var frmAgregar = document.getElementById("frmAgregar");
        frmAgregar.submit();
    }
</script>

PruebasRazor/Views/Viaje/Editar.cshtml
@model PruebasRazor.Models.ViajeCLS
@{
    ViewBag.Title = "Editar";
    List<SelectListItem> listaBus = (List<SelectListItem>)ViewBag.listaBus;
    List<SelectListItem> listaLugar = (List<SelectListItem>)ViewBag.listaLugar;
}
@using (Html.BeginForm(Html.BeginForm("Editar", "Viaje", FormMethod.Post, new { @id = "frmViaje" })))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ViajeCLS</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.iidViaje, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.iidViaje, new { htmlAttributes = new { @class = "form-control", @readOnly = "true" } })
                @Html.ValidationMessageFor(model => model.iidViaje, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.iidLugarOrigen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("iidLugarOrigen", listaLugar, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.iidLugarOrigen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.iidLugarDestino, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("iidLugarDestino", listaLugar, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.iidLugarDestino, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fechaViaje, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fechaViaje, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fechaViaje, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.iidBus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("iidBus", listaBus, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.iidBus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.numeroAsientosDisponibles, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.numeroAsientosDisponibles, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.numeroAsientosDisponibles, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                    Guardar
                </button>
                @Html.ActionLink("Volver", "Index", "Marca", null, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
}

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">¿Guardar Cambios?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div style="padding:1em">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">CANCELAR</button>
                <button type="button" onclick="Editar()" class="btn btn-primary">ACEPTAR</button>
            </div>
        </div>
    </div>
</div>

<script>
    function Editar() {
        var frmViaje = document.getElementById("frmViaje");
        frmViaje.submit();
    }
</script>

PruebasRazor/Views/Viaje/Index.cshtml
@using PruebasRazor.Models
@model List<ViajeCLS>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@Html.ActionLink("Agregar", "Agregar", "Viaje", null, new { @class = "btn btn-primary" })
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <td>@Html.LabelFor(p => Model[0].iidViaje)</td>
            <td>@Html.LabelFor(p => Model[0].nombreLugarOrigen)</td>
            <td>@Html.LabelFor(p => Model[0].nombreLugarDestino)</td>
            <td>@Html.LabelFor(p => Model[0].nombreBus)</td>
            <td>Operaciones</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.iidViaje</td>
                <td>@item.nombreLugarOrigen</td>
                <td>@item.nombreLugarDestino</td>
                <td>@item.nombreBus</td>
                <td>
                    @Html.ActionLink(" ", "Editar", "Viaje", new { id = @item.iidViaje }, new { @class = "glyphicon glyphicon-edit btn btn-primary" })
                    <button type="button" onclick="mostrarPopup(@item.iidViaje)" class="glyphicon glyphicon-trash btn btn-danger" data-toggle="modal" data-target="#exampleModal">
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>

@using (Html.BeginForm("Eliminar", "Viaje", FormMethod.Post, new { @id = "frmViaje" }))
{
    @Html.Hidden("txtIdViaje")
}

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">¿Guardar Cambios?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div style="padding:1em">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">CANCELAR</button>
                <button type="button" onclick="Aceptar()" class="btn btn-primary">ACEPTAR</button>
            </div>
        </div>
    </div>
</div>

<script>
    function mostrarPopup(idViaje) {
        document.getElementById("txtIdViaje").value = idViaje;
    }
    function Aceptar() {
        var frmViaje = document.getElementById("frmViaje");
        frmViaje.submit();
    }
</script>