PruebasRazor/Models/RolPagina.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebasRazor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolPagina
    {
        public int IIDROLPAGINA { get; set; }
        public Nullable<int> IIDROL { get; set; }
        public Nullable<int> IIDPAGINA { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    
        public virtual Pagina Pagina { get; set; }
        public virtual Rol Rol { get; set; }
    }
}

PruebasRazor/Controllers/RolPaginaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PruebasRazor.Models;

namespace PruebasRazor.Controllers
{
    public class RolPaginaController : Controller
    {
        // GET: RolPagina
        public ActionResult Index()
        {
            listarComboRol();
            List<RolPaginaCLS> listaRol = new List<RolPaginaCLS>();
            using (var bd = new BDPasajeEntities())
            {
                listaRol = (from rolpagina in bd.RolPagina
                            join rol in bd.Rol on rolpagina.IIDROL equals rol.IIDROL
                            join pagina in bd.Pagina
                            on rolpagina.IIDPAGINA equals pagina.IIDPAGINA
                            where rolpagina.BHABILITADO == 1
                            select new RolPaginaCLS
                            {
                                iidrolpagina = rolpagina.IIDROLPAGINA,
                                nombreRol = rol.NOMBRE,
                                nombreMensaje = pagina.MENSAJE
                            }).ToList();
            }
            return View(listaRol);
        }

        public ActionResult Filtrar(int iidrol)
        {
            List<RolPaginaCLS> listaRol = new List<RolPaginaCLS>();
            using (var bd = new BDPasajeEntities())
            {
                if (iidrol == 0)
                {
                    listaRol = (from rolpagina in bd.RolPagina
                                join rol in bd.Rol on rolpagina.IIDROL equals rol.IIDROL
                                join pagina in bd.Pagina
                                on rolpagina.IIDPAGINA equals pagina.IIDPAGINA
                                where rolpagina.BHABILITADO == 1
                                select new RolPaginaCLS
                                {
                                    iidrolpagina = rolpagina.IIDROLPAGINA,
                                    nombreRol = rol.NOMBRE,
                                    nombreMensaje = pagina.MENSAJE
                                }).ToList();
                }
                else 
                {
                    listaRol = (from rolpagina in bd.RolPagina
                                join rol in bd.Rol on rolpagina.IIDROL equals rol.IIDROL
                                join pagina in bd.Pagina
                                on rolpagina.IIDPAGINA equals pagina.IIDPAGINA
                                where rolpagina.BHABILITADO==1
                                && rolpagina.IIDROL == iidrol
                                select new RolPaginaCLS
                                {
                                    iidrolpagina = rolpagina.IIDROLPAGINA,
                                    nombreRol = rol.NOMBRE,
                                    nombreMensaje = pagina.MENSAJE
                                }).ToList();
                }

            }
            return PartialView("_TableRolPagina",listaRol);
        }

        public void listarComboRol()
        {
            List<SelectListItem> lista;
            using (var bd = new BDPasajeEntities())
            {
                lista = (from item in bd.Rol
                         where item.BHABILITADO == 1
                         select new SelectListItem
                         {
                             Text = item.NOMBRE,
                             Value = item.IIDROL.ToString()
                         }).ToList();
                lista.Insert(0, new SelectListItem { Text = "--Seleccione--", Value = "" });
                ViewBag.listaRol = lista;
            }
        }
        public void listarComboPagina()
        {
            List<SelectListItem> lista;
            using (var bd = new BDPasajeEntities())
            {
                lista = (from item in bd.Pagina
                         where item.BHABILITADO == 1
                         select new SelectListItem
                         {
                             Text = item.MENSAJE,
                             Value = item.IIDPAGINA.ToString()
                         }).ToList();
                lista.Insert(0, new SelectListItem { Text = "--Seleccione--", Value = "" });
                ViewBag.listaPagina = lista;
            }
        }
    }
}

PruebasRazor/Views/RolPagina/Index.cshtml
@using PruebasRazor.Models
@model List<RolPaginaCLS>
@{
    ViewBag.Title = "Index";
    List<SelectListItem> listaRol = (List<SelectListItem>)ViewBag.listaRol;
}

<h2>Index</h2>

@using (Ajax.BeginForm("Filtrar", "RolPagina", new AjaxOptions
{
    HttpMethod = "POST",
    UpdateTargetId = "divRolPagina",
    InsertionMode = InsertionMode.Replace
}, new { @id = "frmFiltrado" }))
{
    @Html.DropDownList("iidrol", listaRol, new { @class = "form-control" })

    <div id="divRolPagina">
        @Html.Partial("_TableRolPagina", Model)
    </div>
}

<script>
    var iidrol = document.getElementById("iidrol");
    iidrol.onchange = function () {
        $("#frmFiltrado").trigger("submit");
    }
</script>

PruebasRazor/Views/RolPagina/_TableRolPagina.cshtml
@using PruebasRazor.Models
@model List<RolPaginaCLS> 
        
<table class="table table-bordered table-hover">
<thead>
    <tr>
        <td>@Html.LabelFor(p => Model[0].iidrolpagina)</td>
        <td>@Html.LabelFor(p => Model[0].nombreRol)</td>
        <td>@Html.LabelFor(p => Model[0].nombreMensaje)</td>
    </tr>
</thead>
<tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.iidrolpagina</td>
            <td>@item.nombreRol</td>
            <td>@item.nombreMensaje</td>
        </tr>
    }
</tbody>
</table>