PruebasRazor/Models/Sucursal.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebasRazor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sucursal()
        {
            this.Bus = new HashSet<Bus>();
        }
    
        public int IIDSUCURSAL { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> FECHAAPERTURA { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bus> Bus { get; set; }
    }
}

PruebasRazor/Controllers/SucursalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PruebasRazor.Models;
using PruebasRazor.Controllers;

namespace PruebasRazor.Controllers
{
    public class SucursalController : Controller
    {
        // GET: Sucursal
        public ActionResult Index(SucursalCLS oSucursalCLS)
        {
            string nombreSucursal = oSucursalCLS.nombre;
            List<SucursalCLS> listaSucursal = null;
            using (var bd = new BDPasajeEntities())
            {
                if (nombreSucursal == null)
                {
                    listaSucursal = (from sucursal in bd.Sucursal
                                     where sucursal.BHABILITADO == 1
                                     select new SucursalCLS
                                     {
                                         iidsucursal = sucursal.IIDSUCURSAL,
                                         nombre = sucursal.NOMBRE,
                                         telefono = sucursal.TELEFONO,
                                         email = sucursal.EMAIL
                                     }).ToList();
                }
                else {
                    listaSucursal = (from sucursal in bd.Sucursal
                                     where sucursal.BHABILITADO == 1
                                     && sucursal.NOMBRE.Contains(nombreSucursal)
                                     select new SucursalCLS
                                     {
                                         iidsucursal = sucursal.IIDSUCURSAL,
                                         nombre = sucursal.NOMBRE,
                                         telefono = sucursal.TELEFONO,
                                         email = sucursal.EMAIL
                                     }).ToList();
                }
            }
            return View(listaSucursal);
        }

        public ActionResult Agregar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Eliminar(int txtIdSucursal)
        {
            using (var bd = new BDPasajeEntities())
            {
                Sucursal oSucursal = bd.Sucursal.Where(p => p.IIDSUCURSAL.Equals(txtIdSucursal)).First();
                oSucursal.BHABILITADO = 0;
                bd.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public ActionResult Editar(int id)
        {
            SucursalCLS oSucursalCLS = new SucursalCLS();
            using (var bd = new BDPasajeEntities())
            {
                Sucursal oSucursal = bd.Sucursal.Where(p => p.IIDSUCURSAL.Equals(id)).First();
                oSucursalCLS.iidsucursal = oSucursal.IIDSUCURSAL;
                oSucursalCLS.nombre = oSucursal.NOMBRE;
                oSucursalCLS.direccion = oSucursal.DIRECCION;
                oSucursalCLS.telefono = oSucursal.TELEFONO;
                oSucursalCLS.email = oSucursal.EMAIL;
                oSucursalCLS.fechaApertura = (DateTime)oSucursal.FECHAAPERTURA;
            }
            return View(oSucursalCLS);
        }

        [HttpPost]
        public ActionResult Editar(SucursalCLS oSucursalCLS)
        {
            int nregistrosEncontrados = 0;
            string nombreSucursal = oSucursalCLS.nombre;
            int idSucursal = oSucursalCLS.iidsucursal;
            using (var bd = new BDPasajeEntities())
            {
                nregistrosEncontrados = bd.Sucursal.Where(p => p.NOMBRE.Equals(nombreSucursal) && !p.IIDSUCURSAL.Equals(idSucursal)).Count();
            }
            if (!ModelState.IsValid || nregistrosEncontrados >= 1)
            {
                if (nregistrosEncontrados >= 1) oSucursalCLS.mensajeError = "ya existe la sucursal";
                return View(oSucursalCLS);
            }
            using (var bd = new BDPasajeEntities())
            {
                Sucursal oSucursal = bd.Sucursal.Where(p => p.IIDSUCURSAL.Equals(idSucursal)).First();
                oSucursal.NOMBRE = oSucursalCLS.nombre;
                oSucursal.DIRECCION = oSucursalCLS.direccion;
                oSucursal.TELEFONO = oSucursalCLS.telefono;
                oSucursal.EMAIL = oSucursalCLS.email;
                oSucursal.FECHAAPERTURA = oSucursalCLS.fechaApertura;
                bd.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Agregar(SucursalCLS oSucursalCLS)
        {
            int nregistrosEncontrados = 0;
            string nombreSucursal = oSucursalCLS.nombre;
            using (var bd = new BDPasajeEntities())
            {
                nregistrosEncontrados = bd.Sucursal.Where(p => p.NOMBRE.Equals(nombreSucursal)).Count();
            }
            if (!ModelState.IsValid || nregistrosEncontrados >= 1)
            {
                if (nregistrosEncontrados >= 1) oSucursalCLS.mensajeError = "ya existe la sucursal a ingresar";
                return View(oSucursalCLS);
            }
            using (var bd = new BDPasajeEntities())
            {
                Sucursal oSucursal = new Sucursal();
                oSucursal.NOMBRE = oSucursalCLS.nombre;
                oSucursal.DIRECCION = oSucursalCLS.direccion;
                oSucursal.TELEFONO = oSucursalCLS.telefono;
                oSucursal.EMAIL = oSucursalCLS.email;
                oSucursal.FECHAAPERTURA = oSucursalCLS.fechaApertura;
                oSucursal.BHABILITADO = 1;
                bd.Sucursal.Add(oSucursal);
                bd.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

PruebasRazor/Views/Sucursal/Agregar.cshtml
@using PruebasRazor.Models
@model SucursalCLS
@{
    ViewBag.Title = "Agregar";
}

<h2>Agregar</h2>
<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Agregar", "Sucursal", FormMethod.Post, new { @id = "frmAgregar" }))
        {
            <div>
                @Html.LabelFor(p => p.nombre)
                @Html.TextBoxFor(p => p.nombre, new { @class = "form-control" })
                @Html.ValidationMessage("nombre", new { @class = "text-danger" })
                @if (Model != null && Model.mensajeError != null)
                {
                    @Html.Label(Model.mensajeError, new { @class = "text-danger" })
                }
            </div>
            <div>
                @Html.LabelFor(p => p.direccion)
                @Html.TextBoxFor(p => p.direccion, new { @class = "form-control" })
                @Html.ValidationMessage("direccion", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.telefono)
                @Html.TextBoxFor(p => p.telefono, new { @class = "form-control" })
                @Html.ValidationMessage("telefono", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.email)
                @Html.TextBoxFor(p => p.email, new { @class = "form-control" })
                @Html.ValidationMessage("email", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.fechaApertura)
                @Html.EditorFor(p => p.fechaApertura, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessage("fechaApertura", new { @class = "text-danger" })
            </div>
            <div style="margin:auto">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                    Guardar
                </button>
                @Html.ActionLink("Volver", "Index", "Sucursal", null, new { @class = "btn btn-danger" })
            </div>
        }
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">¿Guardar Cambios?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div style="padding:1em">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">CANCELAR</button>
                <button type="button" onclick="Agregar()" class="btn btn-primary">ACEPTAR</button>
            </div>
        </div>
    </div>
</div>

<script>
    function Agregar() {
        var frmAgregar = document.getElementById("frmAgregar");
        frmAgregar.submit();
    }
</script>

PruebasRazor/Views/Sucursal/Editar.cshtml
@using PruebasRazor.Models
@model SucursalCLS
@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>
<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Editar", "Sucursal", FormMethod.Post, new { @id = "frmEditar" }))
        {
            <div>
                @Html.LabelFor(p => p.iidsucursal)
                @Html.TextBoxFor(p => p.iidsucursal, new { @class = "form-control", @readOnly = true })
                @Html.ValidationMessage("iidsucursal", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.nombre)
                @Html.TextBoxFor(p => p.nombre, new { @class = "form-control" })
                @Html.ValidationMessage("nombre", new { @class = "text-danger" })
                @if (Model != null && Model.mensajeError != null)
                { 
                    @Html.Label(Model.mensajeError,new { @class="text-danger"})
                }
            </div>
            <div>
                @Html.LabelFor(p => p.direccion)
                @Html.TextBoxFor(p => p.direccion, new { @class = "form-control" })
                @Html.ValidationMessage("direccion", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.telefono)
                @Html.TextBoxFor(p => p.telefono, new { @class = "form-control" })
                @Html.ValidationMessage("telefono", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.email)
                @Html.TextBoxFor(p => p.email, new { @class = "form-control" })
                @Html.ValidationMessage("email", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.fechaApertura)
                @Html.EditorFor(p => p.fechaApertura, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessage("fechaApertura", new { @class = "text-danger" })
            </div>
            <div style="margin:auto">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                    Guardar
                </button>
                @Html.ActionLink("Volver", "Index", "Sucursal", null, new { @class = "btn btn-danger" })
            </div>
        }
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">¿Guardar Cambios?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div style="padding:1em">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">CANCELAR</button>
                <button type="button" onclick="Agregar()" class="btn btn-primary">ACEPTAR</button>
            </div>
        </div>
    </div>
</div>

<script>
    function Agregar() {
        var frmEditar = document.getElementById("frmEditar");
        frmEditar.submit();
    }
</script>

PruebasRazor/Views/Sucursal/Index.cshtml
@using PruebasRazor.Models
@model List<SucursalCLS>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@Html.ActionLink("Agregar", "Agregar", "Sucursal", null, new { @class = "btn btn-primary" })

@using (Html.BeginForm("Index", "Sucursal", FormMethod.Get, new { @id="frmBusqueda" }))
{

    @Html.Label("Ingrese nombre de sucursal")
    @Html.TextBox("nombre")
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <td>@Html.LabelFor(p => Model[0].iidsucursal)</td>
                <td>@Html.LabelFor(p => Model[0].nombre)</td>
                <td>@Html.LabelFor(p => Model[0].telefono)</td>
                <td>@Html.LabelFor(p => Model[0].email)</td>
                <td>Operaciones</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.iidsucursal</td>
                    <td>@item.nombre</td>
                    <td>@item.telefono</td>
                    <td>@item.email</td>
                    <td>
                        @Html.ActionLink(" ", "Editar", "Sucursal", new { id = @item.iidsucursal }, new { @class = "glyphicon glyphicon-edit btn btn-primary" })
                        <button type="button" onclick="mostrarPopup(@item.iidsucursal)" class="glyphicon glyphicon-trash btn btn-danger" data-toggle="modal" data-target="#exampleModal">
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
@using (Html.BeginForm("Eliminar", "Sucursal", FormMethod.Post, new { @id = "frmSucursal" }))
{
    @Html.Hidden("txtIdSucursal")
}

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">¿Guardar Cambios?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div style="padding:1em">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">CANCELAR</button>
                <button type="button" onclick="Aceptar()" class="btn btn-primary">ACEPTAR</button>
            </div>
        </div>
    </div>
</div>

<script>
    function mostrarPopup(idSucursal) {
        document.getElementById("txtIdSucursal").value = idSucursal;
    }
    function Aceptar() {
        var frmSucursal = document.getElementById("frmSucursal");
        frmSucursal.submit();
    }
    var nombre = document.getElementById("nombre");
    nombre.onkeyup = function () {
        var frmBusqueda = document.getElementById("frmBusqueda");
        frmBusqueda.submit();
    }
</script>